version: '3.9'

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: monviso-db-local
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monviso-db-local
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
