name: CI

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn ci
      - run: yarn test:cov
      - uses: codecov/codecov-action@v2

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn ci
      - run: yarn lint
      - run: yarn build
